### ISSUE TITLE
建议还是不要自己写原生sql，重构用上ORM吧

### ISSUE THREAD

**Issue by dodgepudding** [wstmall/wstmall#1]
看了下代码，前端还好，后端model很多堆砌起来的sql处理，本来就在model里的方法还重新调用一次D实例方法调用自己，直接用$this调用就好了。
sql处理不是不好，但一些提交参数没有过滤之下很多容易被注入。
随便扫了一眼其中一个拼接的sql就有失误。
Apps/Home/Model/GoodsCatsModel.class.php这里的getGoodsCatsAndGoodsForIndex方法，
查询二级分类下的商品这条sql，left join了goods_attributes表, 主表goods跟goods_attributes表是one to many关系，但这样join了同一个商品当有多个属性值就会在列表里重复显示多次。如果用TP自带的Relation模型，就会聚合到同一条的数组属性值组集合里。

**Comment by wstmall** [comment]
您好，您的建议我们已经收到，在接下来的版本中，我们将改善这种情况。感谢您的建议，祝您新年快乐！
